# Part 3 of 3 of the jLab cross-check harness (jlab_crosscheck_*).
#
# Diffs our own rotary_ridge_properties output against jLab's REAL
# eddyridges.m output (from jlab_crosscheck_eddyridges.m) on the identical
# 28 segments, ridge-by-ridge -- not against our own metrics, and not
# against GOMED directly (GOMED itself is also reported here, as a sanity
# check that jLab's own re-run reproduces it, since GOMED was generated by
# an unknown exact historical parameter set on the larger GulfDriftersAll).
#
# For each case: find the jLab ridge with the best temporal overlap
# against the manifest's true GOMED window (that's "the" target ridge),
# then find the best-overlapping ridge in OUR OWN output. Reports, per
# case: jLab-vs-GOMED agreement (sanity), ours-vs-jLab agreement (the
# actual port-fidelity test), and OUR fragment count around that window
# (how many separate ridges we produce that all overlap jLab's one ridge
# -- 1 is correct, >1 means we're still fragmenting something jLab treats
# as continuous).
#
# Usage: julia --project=envs/cpu scripts/jlab_crosscheck_compare.jl
# Prerequisite: scripts/jlab_crosscheck_export.jl, then
#               scripts/jlab_crosscheck_eddyridges.m in MATLAB.

using ValTools, ValTools.JLab
using DelimitedFiles, Statistics, Printf

const OUTDIR = joinpath(@__DIR__, "..", "results", "jlab_crosscheck")

function read_manifest(path)
    raw, hdr = readdlm(path, ','; header=true)
    rows = NamedTuple[]
    for r in eachrow(raw)
        push!(rows, (ridge_id=Int(r[1]), segment_id=Int(r[2]), N=Int(r[3]),
                      gomed_t0=Float64(r[4]), gomed_t1=Float64(r[5]), gomed_L=Float64(r[6]),
                      gomed_omega=Float64(r[7]), gomed_xi=Float64(r[8]), gomed_R=Float64(r[9])))
    end
    return rows
end

function read_jlab_ridges(path)
    raw, hdr = readdlm(path, ','; header=true)
    by_case = Dict{Int,Vector{NamedTuple}}()
    for r in eachrow(raw)
        rid = Int(r[1])
        push!(get!(by_case, rid, NamedTuple[]),
              (t0=Float64(r[3]), t1=Float64(r[4]), npts=Int(r[5]),
               L=Float64(r[6]), omega_day=Float64(r[7]), xi=Float64(r[8])))
    end
    return by_case
end

jaccard(a0, a1, b0, b1) = begin
    inter = max(0.0, min(a1, b1) - max(a0, b0))
    uni = max(a1, b1) - min(a0, b0)
    uni > 0 ? inter / uni : 0.0
end

manifest = read_manifest(joinpath(OUTDIR, "manifest.csv"))
jlab_by_case = read_jlab_ridges(joinpath(OUTDIR, "jlab_ridges.csv"))
data = load_gulfdrifters(; download=false)
id_to_idx = Dict(data.id[i] => i for i in 1:data.n_drifters)

@printf("%-4s %-8s | %6s %6s | %6s %6s %6s | %5s %6s\n",
        "idx", "ridge", "jl_jac", "jl_L%", "our_jac", "our_L%", "our_om%", "frag", "status")

function run_comparison(manifest, jlab_by_case, data, id_to_idx)
jl_gomed_jacc = Float64[]
our_jl_jacc = Float64[]
n_frag1 = 0
n_matched = 0

for (idx, m) in enumerate(manifest)
    jl_ridges = get(jlab_by_case, m.ridge_id, NamedTuple[])
    isempty(jl_ridges) && continue

    # jLab ridge best matching GOMED's own window (sanity check)
    jl_best = jl_ridges[argmax([jaccard(m.gomed_t0, m.gomed_t1, r.t0, r.t1) for r in jl_ridges])]
    jl_jacc = jaccard(m.gomed_t0, m.gomed_t1, jl_best.t0, jl_best.t1)
    jl_Lpct = 100 * (jl_best.L - m.gomed_L) / m.gomed_L
    push!(jl_gomed_jacc, jl_jacc)

    # Our own ridges on this segment
    i = id_to_idx[m.segment_id]
    u, v, t, lat, lon = data.u[i], data.v[i], data.time[i], data.lat[i], data.lon[i]
    f0 = 2π * inertial_frequency(mean(lat))
    # jLab's real eddyridges.m wavelet-transforms POSITION (spheretrans.m:
    # [wx,wy,wz]=wavetrans(x,y,z,...) on the 3D Cartesian projection of
    # lat/lon), not velocity -- confirmed by reading spheretrans.m directly
    # (2026-08-01, "ValTools 7"). Simple fixed local tangent-plane
    # approximation (not jLab's time-varying-center reprojection, but
    # enough to test the hypothesis): x=R*cos(lat0)*(lon-lon0),
    # y=R*(lat-lat0), R=6371 km.
    R_EARTH = 6371.0
    lat0, lon0 = mean(lat), mean(lon)
    x_km = R_EARTH .* cosd(lat0) .* deg2rad.(lon .- lon0)
    y_km = R_EARTH .* deg2rad.(lat .- lat0)
    rr = rotary_ridge_properties(x_km, y_km; f_coriolis=f0, fmax_ratio=2, fmin_ratio=1/64, boundary=:mirror)
    our_cands = [(t0=t[e.start], t1=t[e.stop], L=e.L, omega_ast=e.omega_ast_bar) for e in rr]

    if isempty(our_cands)
        @printf("%-4d %-8d | %6.2f %6.1f | %6s %6s %6s | %5d %6s\n",
                idx, m.ridge_id, jl_jacc, jl_Lpct, "-", "-", "-", 0, "MISS")
        continue
    end
    jaccs = [jaccard(jl_best.t0, jl_best.t1, c.t0, c.t1) for c in our_cands]
    best_i = argmax(jaccs)
    our_jacc = jaccs[best_i]
    our_best = our_cands[best_i]
    our_Lpct = 100 * (our_best.L - jl_best.L) / jl_best.L
    our_om_day = our_best.omega_ast * f0 * 24  # rad/sample(hr) * hr/rad... wait omega_ast is nondim; compare sign+rough scale only
    n_frag = count(j -> j > 0.05, jaccs)  # how many of our ridges overlap jLab's ridge at all

    our_jacc > 0.3 && (n_matched += 1)
    n_frag == 1 && our_jacc > 0.3 && (n_frag1 += 1)
    push!(our_jl_jacc, our_jacc)

    status = our_jacc > 0.6 ? "good" : our_jacc > 0.3 ? "partial" : "poor"
    @printf("%-4d %-8d | %6.2f %6.1f | %6.2f %6.1f %6s | %5d %6s\n",
            idx, m.ridge_id, jl_jacc, jl_Lpct, our_jacc, our_Lpct, "-", n_frag, status)
end

@printf("\n=== jLab vs GOMED (sanity: does re-running jLab reproduce GOMED?) ===\n")
@printf("mean Jaccard: %.3f, median: %.3f, n>=0.6: %d/%d\n",
        mean(jl_gomed_jacc), median(jl_gomed_jacc), count(>=(0.6), jl_gomed_jacc), length(jl_gomed_jacc))

@printf("\n=== Ours vs jLab (the actual port-fidelity test) ===\n")
@printf("mean Jaccard: %.3f, median: %.3f, n>=0.6 (good): %d/%d, n matched (>0.3): %d/%d\n",
        mean(our_jl_jacc), median(our_jl_jacc), count(>=(0.6), our_jl_jacc), length(our_jl_jacc),
        n_matched, length(our_jl_jacc))
@printf("Clean 1:1 match (no fragmentation, jaccard>0.3): %d/%d\n", n_frag1, length(our_jl_jacc))
end

run_comparison(manifest, jlab_by_case, data, id_to_idx)
